name: Regression E2E Tests
on: push #When a push event occurs, actions will be triggered
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        run: cypress-io/github-action@v5